### ISSUE TITLE
Infinitely redirect to https://passkeys.2fa.directory/int/

### ISSUE THREAD

**Issue by CoelacanthusHex** [2factorauth/passkeys.2fa.directory#3]
Steps to reproduce:
1. Open https://passkeys.2fa.directory/ or append any string to it like https://passkeys.2fa.directory/cn or https://passkeys.2fa.directory/us
2. It redirects to https://passkeys.2fa.directory/int/
3. And then it redirects to https://passkeys.2fa.directory/int/ infinitely

It can be reproduced in Firefox, Chromium, and cURL. I'm on Arch Linux.

https://2fa.directory doesn't have the same issue.

**Comment by hkamran80** [comment]
@Carlgo11, did we break the redirect script?

**Comment by Carlgo11** [comment]
Yeah something certainly broke. I've reverted back to an older build so that the page at least loads.
